
branches:
 only:
  - master

language: python

matrix:
  include:

    - os: linux
      python: "3.5.2"

    - os: linux
      python: "2.7"

cache:
  directories:
    - $HOME/.pyenv/versions/3.5.2
    - $HOME/.pyenv/versions/2.7.12
    - $HOME/downloads

install:
  - pip install flake8

script:
  - flake8
