
branches:
 only:
  - master

language: python

matrix:
  include:

    - os: linux
      python: "3.5.2"

    - os: linux
      python: "2.7"

install:
  - pip install -r requirements-dev.txt
  - pip install tox-travis

script:
  - tox
